# Autogenerated from /Users/cschen/llvm/test/clang/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)


import sys

config.llvm_src_root = path(r"/Users/cschen/llvm/test/llvm")
config.llvm_obj_root = path(r"/Users/cschen/llvm/test/build")
config.llvm_tools_dir = path(r"/Users/cschen/llvm/test/build/./bin")
config.llvm_libs_dir = path(r"/Users/cschen/llvm/test/build/./lib")
config.llvm_shlib_dir = path(r"/Users/cschen/llvm/test/build/./lib")
config.llvm_plugin_ext = ".dylib"
config.lit_tools_dir = path(r"")
config.clang_obj_root = path(r"/Users/cschen/llvm/test/build/tools/clang")
config.clang_src_dir = path(r"/Users/cschen/llvm/test/clang")
config.clang_tools_dir = path(r"/Users/cschen/llvm/test/build/./bin")
config.host_triple = "arm64-apple-darwin20.6.0"
config.target_triple = "cpu0-unknown-elf"
config.host_cxx = "/opt/homebrew/opt/llvm/bin/clang++"
config.llvm_use_sanitizer = ""
config.have_zlib = 1
config.clang_arcmt = 1
config.clang_default_cxx_stdlib = ""
config.clang_staticanalyzer = 1
config.clang_staticanalyzer_z3 = ""
config.clang_examples = 0
config.enable_shared = 1
config.enable_backtrace = 1
config.enable_experimental_new_pass_manager = 0
config.enable_threads = 1
config.host_arch = "arm64"
config.python_executable = "/opt/homebrew/Frameworks/Python.framework/Versions/3.9/bin/python3.9"
config.use_z3_solver = lit_config.params.get('USE_Z3_SOLVER', "")
config.has_plugins = 1
config.clang_vendor_uti = "org.llvm.clang"

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.clang_tools_dir = config.clang_tools_dir % lit_config.params
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_shlib_dir = config.llvm_shlib_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(config.clang_src_dir, "test/lit.cfg.py"))
